remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "How to succeed at MD'ing by actually trying"
description: "A guide to Music Directing by David Lang"
show_downloads: "false"
